[book]
title = "Learning Haskell by building a static blog generator"
description = "A project-oriented online book about Haskell"
authors = ["Gil Mizrahi"]
language = "en"
multilingual = false
src = "src"
git-repository-url = "https://github.com/soupi/learn-haskell-blog-generator"
git-repository-icon = "fa-github"
